language: node_js
node_js:
- '12'
- '10'
cache:
  directories:
  - node_modules
notifications:
  email: false
install:
- yarn
script:
- yarn test
- yarn build
after_success:
  - yarn travis-deploy-once "yarn semantic-release && yarn build"
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: dist
  on:
    branch: master
    condition: $TRAVIS_NODE_VERSION = "12"